#!/usr/bin/env bash

prefix="vcwc_grafana_traefik__$1"
prefix="vcwc_grafana_traefik__$1"

if [[ "vcwc_grafana_traefik__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_grafana_traefik__grafana_grafana_volume
fi

if [[ "vcwc_grafana_traefik__grafana_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_grafana_traefik__grafana_nginx_config_volume
fi

if [[ "vcwc_grafana_traefik__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_grafana_traefik__grafana_grafana_volume:/var/lib/grafana ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd tar -C / -xvf /source/vcwc/grafana/traefik/_module/volumes/grafana_grafana_volume.tar
fi

if [[ "vcwc_grafana_traefik__grafana_nginx_config_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_grafana_traefik__grafana_nginx_config_volume:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/grafana/traefik/_module/volumes/grafana_nginx_config_volume/* /vcw/pwd
fi
