#!/usr/bin/env bash

prefix="vcwc_grafana_traefik__$1"
prefix="vcwc_grafana_traefik__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_grafana_traefik__grafana_grafana_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_grafana_traefik__grafana_grafana_volume"
		result=$(docker volume ls | grep "vcwc_grafana_traefik__grafana_grafana_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_grafana_traefik__grafana_nginx_config_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_grafana_traefik__grafana_nginx_config_volume"
		result=$(docker volume ls | grep "vcwc_grafana_traefik__grafana_nginx_config_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
