#!/usr/bin/env bash

prefix="vcw_module_vcwc_grafana__$1"
prefix="vcw_module_vcwc_grafana__$1"

if [[ "vcw_module_vcwc_grafana__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_grafana__grafana_grafana_volume
fi

if [[ "vcw_module_vcwc_grafana__grafana_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_grafana__grafana_grafana_volume:/var/lib/grafana ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/grafana/_module/volumes/grafana_grafana_volume.tar
fi
