---
version: '3'
services:

# START SERVICE vcwc/grafana
  grafana:
    image: ${VCW_REGISTRY}grafana/grafana:7.2.1
    environment: ['GF_SERVER_SERVE_FROM_SUB_PATH=${VCW_STACK_GRAFANA_MODULE_GRAFANA_SERVE_FROM_SUB_PATH}', 'GF_SECURITY_ALLOW_EMBEDDING=true', 'GF_AUTH_ANONYMOUS_ENABLED=true', 'GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.', 'GF_AUTH_ANONYMOUS_ORG_ROLE=${VCW_STACK_GRAFANA_MODULE_GRAFANA_AUTH_ANONYMOUS_ORG_ROLE}', 'GF_LOG_MODE=console', 'GF_LOG_CONSOLE_FORMAT=text', 'GF_LOG_LEVEL=${VCW_STACK_GRAFANA_MODULE_GRAFANA_LOG_LEVEL}', 'GF_SERVER_ROOT_URL=${VCW_STACK_GRAFANA_MODULE_GRAFANA_SERVER_ROOT_URL}']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_grafana_volume:/var/lib/grafana']
    ports: [${VCW_STACK_GRAFANA_PORTS_GRAFANA_PORT}:3000]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_GRAFANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_GRAFANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_GRAFANA_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/grafana

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_grafana_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
